apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: todo-secretStore
  namespace: todo
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /components/todo-secrets.json
    - name: nestedSeparator
      value: ":"
