[dependencies]
 
  tea = { git = "https://gitcode.com/yishengTH/tea.git", branch = "cj-0.53.13" }
  naiveteaset = { git = "https://gitcode.com/zhangyin_gitcode/naiveteaset.git", branch = "master" }
  naiveioc = { git = "https://gitcode.com/zhangyin_gitcode/naiveioc.git", branch = "master" }
  naivemediator = { git = "https://gitcode.com/zhangyin_gitcode/naivemediator.git", branch = "master" }
  naivevalidation = { git = "https://gitcode.com/zhangyin_gitcode/naivevalidation.git", branch = "master" }
  naivesqlbuilder = { git = "https://gitcode.com/zhangyin_gitcode/naivesqlbuilder.git", branch = "5313" }
  sql_builder = { git = "https://gitcode.com/zhangyin_gitcode/sql_builder.git", branch = "5313" }
  mysqlclient4cj = { git = "https://gitcode.com/zhangyin_gitcode/mysql-driver.git", branch = "for-cj-0.53.13" }
  cjjson = { git = "https://gitcode.com/Cangjie-TPC/cangjieJSON.git", output-type = "static" }
  dapr_cangjie_sdk = { git = "https://gitcode.com/PermissionDog/dapr-cangjie-sdk.git", branch = "cj_0.53.13" }
  dapr_tea = { git = "https://gitcode.com/PermissionDog/dapr_tea.git", branch = "cj-0.53.13" }
  naiveserviceresult = { git = "https://gitcode.com/zhangyin_gitcode/naiveserviceresult.git" }
  naivelogger = { git = "https://gitcode.com/zhangyin_gitcode/naivelogger.git", branch = "master" }
  naivelogger_seq = { git = "https://gitcode.com/zhangyin_gitcode/naivelogger_seq.git", branch = "master" }
  
[package]
  cjc-version = "0.53.18"
  compile-option = "--debug-macro"
  description = "nothing here"
  link-option = ""
  name = "text_photo_list_api"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
